---
title: "Final Project"
output: pdf_document
---

```{r, echo=FALSE}
library(ggplot2)
library(gridExtra)
library(dplyr)
library(reshape2)
library(Ternary)
source("functions.R")
source("binary_sampler.R")
source("plot_functions.R")
# import protein altering sheet
raw_PA <- readxl::read_excel("data/ukb_biomarker_supp.xlsx", sheet="ST7", skip=1)
# import noncoding sheet
raw_NC <- readxl::read_excel("data/ukb_biomarker_supp.xlsx", sheet="ST8", skip=1)
df <- bind_rows(raw_PA, raw_NC)
```

## Summary statistics summary
```{r}
# variant count frequencies
p1 <- ggplot(as.data.frame(table(df$ID)), aes(x=Freq)) + 
  geom_histogram(bins=25, color="white") + 
  ggtitle("Freq of counts of # of traits variants affect") + 
  xlab("# of traits affected") + ylab("Frequency") + theme_minimal()
# histogram of betas
p2 <- ggplot(df, aes(x=BETA)) + geom_histogram(aes(y=..density..),bins=100,color="white") + 
  theme_minimal() + ggtitle("Distr of betas") + xlim(c(-0.5,0.5))
# try to fit a normal and see how it looks
d_estimate <- MASS::fitdistr(df$BETA, "normal")$estimate 
p2 <- p2 + stat_function(fun=dnorm, args=d_estimate, color="red")
grid.arrange(p1,p2,ncol=2)
```

## Rint
```{r}
df$BETA_rint <- qnorm((rank(df$BETA)-0.5)/length(df$BETA))
ggplot(df, aes(x=BETA_rint)) + geom_histogram(bins=15, color="white") + theme_minimal() + ggtitle("PA")
```

```{r}
df$Trait_combined <- paste0(df$Trait, " (", df$`Trait category`, ")")
# num traits affected each variant affects
variants_binary <- table(df$ID, df$Trait, useNA="no")
counts <- data.frame(rowSums(variants_binary))
counts <- cbind(variant=rownames(counts), counts)
rownames(counts) <- 1:nrow(counts)
# num variants that influence more than one trait
nrow(counts[counts$rowSums.variants_binary.>1,])

# key of trait to pre-defined category
category_key <- df %>% distinct(Trait, .keep_all = TRUE) %>% select(Trait, `Trait category`)
category_key <- category_key[order(category_key$Trait),]
category_key$Trait_short <- c("alt", "alb", "akp", "apA", "apB", "ast", "astalt", "crp", "cal", "chol", "crea", "creaU", "cysC", "dbili", "eGFR", "ggt", "glu", "HbA1c", "HDL", "IGF1", "LDL", "LpA", "malbU", "nalb", "phos", "potU", "SHBG", "sodU", "test", "tbili", "tprot", "trig", "urate", "urea", "vitD")
```

# Binary sample

### K = 6
```{r}
niter <- 1000
res <- gibbs(variants_binary, K=6, R=ncol(variants_binary), niter=niter)
# visualize gibbs trajectory for effect frequencies
plot_gibbs_chain(res, 6)
```


```{r, include=FALSE}
# try several chains
# for (i in 1:10) {
#   print(gibbs(variants_binary, K=6, R=ncol(variants_binary), niter=60)$pi[60,])
# }
pi_mean <- colSums(res$pi[-(1:50),])/nrow(res$pi[-(1:50),])
# get mean of P
X <- list(res$P[,,-(1:50)])
Y <- do.call(cbind, X)
Y <- array(Y, dim=c(dim(X[[1]]), length(X)))
P_mean <- apply(Y, c(1, 2), mean, na.rm = TRUE)
```


```{r}
pi_mean
# df cols: ID, assignment, P(1), P(2), P(3), P(4), P(5), P(6)
assignments <- get_cluster_assignments(data=df, x=variants_binary, res=res, niter=niter)
```

```{r}
# stacked barplot of assignment probabilities (see plots folder for full plot)
# note: these are not admixture proportions, the variants can't be decomposed into something analagous to loci
# stacked_barplot(assignments, do_save=T, fname="binary_stacked_by_assignment.png", orderby="assignment") # takes a moment to run
# stacked_barplot(assignments, do_save=T, fname="binary_stacked_by_position.png", orderby="position") # takes a moment to run
# idk why the axis labels aren't showing up
stacked_barplot(assignments, n=100, orderby="assignment")
stacked_barplot(assignments, n=100, orderby="position")
```

```{r}
# proportion of variants in each cluster for each trait
df$assignment <- sapply(df$ID, function(x) {assignments[assignments$ID==x, ]$assignment})
t <- table(df$Trait_combined, df$assignment)
# doesn't seem to nec match pre-defined categories but looks like it makes biological sense...
t_prop <- table(df$Trait, df$assignment)/rowSums(t)
t_prop <- as.data.frame.matrix(t_prop)
rownames(t_prop) <- category_key$Trait_short

t_prop
```

```{r}
# ternary plot abstraction TO DO:
# iterate through traits, take >0.1 cluster prob and put onto triangle
# maybe use ggtern to plot and make sure labels dont overlap
plot_triangles(t_prop, n_top=4, category_key=category_key)
```

### K = 3
```{r}
niter3 <- 500
res3 <- gibbs(variants_binary, K=3, R=ncol(variants_binary), niter=niter3)
assignments3 <- get_cluster_assignments(x=variants_binary, res=res3, niter=niter3)
stacked_barplot(assignments3, do_save=T, fname="binary_stacked_by_assignment_k=3.png", orderby="assignment") # takes a moment to run
```
```{r}
# stacked_barplot(assignments3)
# examine by trait
df$assignment3 <- sapply(df$ID, function(x) {assignments3[assignments3$ID==x, ]$assignment})
t3 <- table(df$Trait, df$assignment3)
round(table(df$Trait, df$assignment3)/rowSums(t3), 2)
```

### K = 4
```{r}
niter4 <- 500
res4 <- gibbs(variants_binary, K=4, R=ncol(variants_binary), niter=niter4)
assignments4 <- get_cluster_assignments(x=variants_binary, res=res4, niter=niter4)
# stacked_barplot(assignments4, do_save=T, fname="binary_stacked_by_assignment_k=4.png", orderby="assignment") # takes a moment to run
```

```{r}
df$assignment4 <- sapply(df$ID, function(x) {assignments4[assignments4$ID==x, ]$assignment})
t_prop4 <- table(df$Trait, df$assignment4)/rowSums(table(df$Trait, df$assignment4))
t_prop4 <- as.data.frame.matrix(t_prop4)
rownames(t_prop4) <- category_key$Trait_short
plot_triangles(t_prop4, n_top=4, category_key=category_key)
```

### K = 5
```{r}
niter5 <- 500
res5 <- gibbs(variants_binary, K=5, R=ncol(variants_binary), niter=niter5)
assignments5 <- get_cluster_assignments(x=variants_binary, res=res5, niter=niter5)
stacked_barplot(assignments5, do_save=T, fname="binary_stacked_by_assignment_k=5.png", orderby="assignment") # takes a moment to run
```

```{r}
df$assignment5 <- sapply(df$ID, function(x) {assignments5[assignments5$ID==x, ]$assignment})
t_prop5 <- table(df$Trait, df$assignment5)/rowSums(table(df$Trait, df$assignment5))
t_prop5 <- as.data.frame.matrix(t_prop5)
rownames(t_prop5) <- category_key$Trait_short
p_list <- plot_triangles(t_prop5, n_top=4, category_key=category_key)
```

### K = 7
```{r}
niter5 <- 500
res5 <- gibbs(variants_binary, K=5, R=ncol(variants_binary), niter=niter5)
assignments5 <- get_cluster_assignments(x=variants_binary, res=res5, niter=niter5)
stacked_barplot(assignments5, do_save=T, fname="binary_stacked_by_assignment_k=5.png", orderby="assignment") # takes a moment to run
```

```{r}
df$assignment5 <- sapply(df$ID, function(x) {assignments5[assignments5$ID==x, ]$assignment})
t_prop5 <- table(df$Trait, df$assignment5)/rowSums(table(df$Trait, df$assignment5))
t_prop5 <- as.data.frame.matrix(t_prop5)
rownames(t_prop5) <- category_key$Trait_short
plot_triangles(t_prop5, n_top=4, category_key=category_key)
```



### Find posterior for K
```{r}
# refer to appendix of structure paper, not sure this is right
posterior_K_raw(variants_binary, assignments, P_mean, 0.1)

K_mat <- K_inference(variants_binary, 10)
K_mat
```


